### ISSUE TITLE
Please add smithna-pra as a collaborator

### ISSUE THREAD

**Issue by smithna-pra** [githubschool/on-demand-github-pages#1171]
Hello! :wave: 

Please add smithna-pra as a collaborator in this repo.

**Comment by githubteacher** [comment]
:tada: @smithna-pra you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
