### ISSUE TITLE
Add me, please.

### ISSUE THREAD

**Issue by ShonInDim** [githubschool/on-demand-github-pages#1185]

**Comment by githubteacher** [comment]
:tada: @ShonInDim you are now a repository collaborator. :balloon:

**Comment by ShonInDim** [comment]
Hi, @githubteacher ! I just confused a link path to my page: instead of https://shonindim.github.io I was setting up https://shinindim.github.io/takeone...
  Is'it no serious problem?  may be should I change it?

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
