### ISSUE TITLE
Need some push access, please :)

### ISSUE THREAD

**Issue by AlgusDark** [githubschool/on-demand-github-pages#1197]
Hi, I need push access so I can move on this awesome workshop.

Regards from Guadalajara!

**Comment by githubteacher** [comment]
:tada: @AlgusDark you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
