### ISSUE TITLE
Please add me as a collaborator!

### ISSUE THREAD

**Issue by estebancrw** [githubschool/on-demand-github-pages#1199]
https://services.github.com/on-demand/github-cli/add-github-pages-site-showcase

**Comment by githubteacher** [comment]
:tada: @estebancrw you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
