### ISSUE TITLE
Please add me as a collaborator

### ISSUE THREAD

**Issue by hernanrenteria** [githubschool/on-demand-github-pages#1208]
Yo, could you please add me as a collaborator?

**Comment by githubteacher** [comment]
:tada: @hernanrenteria you are now a repository collaborator. :balloon:

**Comment by lamonovichsoftware** [comment]
sure

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
