### ISSUE TITLE
add me as a coloborator

### ISSUE THREAD

**Issue by polisettyManoj** [githubschool/on-demand-github-pages#1290]
Hi

**Comment by githubteacher** [comment]
:tada: @polisettyManoj you are now a repository collaborator. :balloon:

**Comment by polisettyManoj** [comment]
@githubteacher  Thankyou

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
