### ISSUE TITLE
add-github-pages-site-showcase

### ISSUE THREAD

**Issue by cdevitasuse** [githubschool/on-demand-github-pages#1292]
workin on 
https://services.github.com/on-demand/github-desktop/add-github-pages-site-showcase

**Comment by githubteacher** [comment]
:tada: @cdevitasuse you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
