### ISSUE TITLE
Please add me as a collaborator

### ISSUE THREAD

**Issue by Ragmad01** [githubschool/on-demand-github-pages#1327]
Hello :wave:! Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @Ragmad01 you are now a repository collaborator. :balloon:

**Comment by Ragmad01** [comment]
Thanks. I submitted an issue in my repo asking for help. Can you please take a look at that? My repo is Raghavs-Repository.

**Comment by hectorsector** [comment]
@Ragmad01 you just have to rename your repo to `ragmad01.github.io`

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
