### ISSUE TITLE
Add me as a collaborator :)

### ISSUE THREAD

**Issue by gabrielvalandrobetha** [githubschool/on-demand-github-pages#1330]
Please, add me as collaborator of this repo.

**Comment by githubteacher** [comment]
:tada: @gabrielvalandrobetha you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
