### ISSUE TITLE
please add me as a collabaroter

### ISSUE THREAD

**Issue by sravankml** [githubschool/on-demand-github-pages#1352]
hi,please add me

**Comment by githubteacher** [comment]
:tada: @sravankml you are now a repository collaborator. :balloon:

**Comment by sravankml** [comment]
thank you :)

On Monday, July 31, 2017, GitHub Teacher <notifications@github.com> wrote:
> 🎉 @sravankml you are now a repository collaborator. 🎈
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/SwsD4nep3O358Or3o8usND93GcV3lKMB-fTo34B8GuRF0n2A2HrJ391KlL23S7l85oyrBbUfyTzVwtnGvfmT6Yff4TB8zv_NEzwNvFpiiTtjcbSAtLq5bAOGA4sGy0EKMtqkm9TX6ST-oEZfeaCdsfOjFjugSg=s0-d-e1-ft#https://github.com/notifications/beacon/AUC9qhXdVXKxBuPadLbQwQrOfGvJ5hwtks5sTXRsgaJpZM4On88I.gif>

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
