### ISSUE TITLE
_pages directory in atom

### ISSUE THREAD

**Issue by vanessat-SMU** [githubschool/on-demand-github-pages#1411]
@githubteacher 
I can't seem to find the pages directory so that I can add the filename: username.yaml.

**Comment by beardofedu** [comment]
@vanessat-SMU you should see the `_pages` directory right below `_layouts` when you are in Atom. Here is how it looks on my screen:

![image](https://user-images.githubusercontent.com/18329853/29670516-d9644362-88b4-11e7-9cbf-cdaccb952c6c.png)

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
