### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by shuvoxcd01** [githubschool/on-demand-github-pages#1430]
Please, add me as a collaborator.

**Comment by hectorsector** [comment]
You probably haven't been able to continue with the course. Teacherbot has been feeling under the weather, sorry! :face_with_thermometer:

You've now been invited to this repo. Please [accept the invitation](https://github.com/githubschool/on-demand-github-pages/invitations) and you should be able to continue with the [GitHub Desktop](https://services.github.com/on-demand/github-desktop/review-github-flow) or the [command line](https://services.github.com/on-demand/github-cli/github-flow-cli) course.

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
