### ISSUE TITLE
I want to be a collaborator 

### ISSUE THREAD

**Issue by qq1433255094** [githubschool/on-demand-github-pages#1434]
I'm late to check email

**Comment by qq1433255094** [comment]
I need be invitated again

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: teacherbot[bot]<mailto:notifications@github.com>
发送时间: 2017年8月31日 20:33
收件人: githubschool/on-demand-github-pages<mailto:on-demand-github-pages@noreply.github.com>
抄送: qq1433255094<mailto:qq1433255094@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [githubschool/on-demand-github-pages] I want to be a collaborator (#1434)


Hi! I'm the friendly 🤖 of this repo.

We're happy you're here 👋. Everyone is welcome here, so I'm making you a collaborator. This will give you access to commit on this repo. Please accept my invitation<https://github.com/githubschool/open-enrollment-classes-introduction-to-github/invitations> before moving on.

**Comment by hectorsector** [comment]
@qq1433255094 does this link work to accept the invitation? https://github.com/githubschool/on-demand-github-pages/invitations

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
