### ISSUE TITLE
Authentication Failed

### ISSUE THREAD

**Issue by Telmoco** [githubschool/on-demand-github-pages#1477]
![captura de pantalla 6](https://user-images.githubusercontent.com/31928065/30782179-41b4995e-a12d-11e7-866f-7271be8e5b78.png)
D: @githubteacher

**Comment by Telmoco** [comment]
Problem solved after waiting a while!

**Comment by mberasategi** [comment]
Kaixo @Telmoco , ya has terminado la actividad así que voy a cerrar el issue.
