### ISSUE TITLE
Push Access Requesting

### ISSUE THREAD

**Issue by pyshmintsev** [githubschool/on-demand-github-pages#1494]
I have no idea what it's for but I did it as I was told.

**Comment by pyshmintsev** [comment]
'Accept my invitation' failed several times. What should I do now?

**Comment by pyshmintsev** [comment]
@githubteacher I need your help

This push access request closes #1494

**Comment by brianamarie** [comment]
Hi @pyshmintsev! I've cancelled the invite and issued a new one: https://github.com/githubschool/on-demand-github-pages/invitations

Please let me know if this still doesn't work, and we'll get something figured out. :smile:

**Comment by pyshmintsev** [comment]
Everything is fine now. The request closes #1494
