### ISSUE TITLE
My last invitation didn't load 

### ISSUE THREAD

**Issue by nicolasfig** [githubschool/on-demand-github-pages#1501]

**Comment by nicolasfig** [comment]
I'm getting a :unicorn:  :sob:

**Comment by brianamarie** [comment]
Hi @nicolasfig! I've reissued your invite. Please let me know if it doesn't work now: https://github.com/githubschool/on-demand-github-pages/invitations

**Comment by nicolasfig** [comment]
It worked thanks :+1:
