### ISSUE TITLE
can i install github desktop offline

### ISSUE THREAD

**Issue by BHASKARRATHOD** [githubschool/on-demand-github-pages#1510]
i want to install github desktop to a pc that does not have internet connection will i be able to do that ?

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.

**Comment by brianamarie** [comment]
@BHASKARRATHOD You would need to package it a separate way - I think it is possible, but I'm sorry to say I can't provide specific instructions.
