### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by andrewj0** [githubschool/on-demand-github-pages#1511]
Describe what you need help with here.
I am confused between the "Make Local Changes GitHub Desktop" page and the "Add Local Commits with GitHub Desktop" page.

I opted for the GitHub themed page and followed instructions, greeted the world, on the 'readme' file on the 'add-index-page' page then committed to 'Master directory'?
Is this right?

I'm not sure what I'm supposed to do with the local GitHub which I can open when I click on the octopus icon docked at the foot of my screen . 

I can't see in the video how the html editor was opened, or whether I'm even supposed to open it. 

Have I made changes to my local repository?

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
