### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by andrewj0** [githubschool/on-demand-github-pages#1512]
Describe what you need help with here.
I am confused between the "Make Local Changes GitHub Desktop" page and the "Add Local Commits with GitHub Desktop" page.

I opted for the GitHub themed page and followed instructions, greeted the world, on the 'readme' file on the  page then committed to 'Master directory'
Is this right?

I'm not sure what I'm supposed to do with the local GitHub that I can open when I click on the octopus icon. 

I can't see in the video how the html editor was opened, or whether I'm even supposed to open it. 

In the section "Review local GitHub flow"  I have successfully created a page 'Andrewj0.yaml' in my _favorite_ text editor and saved it in my _pages folder of my GitHub desktop.  But when trying to sync with the remote GitHub it failed, stating that I do not have permission!!  I don't know why!

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
