### ISSUE TITLE
Why my invitation is invalid?

### ISSUE THREAD

**Issue by zapper123** [githubschool/on-demand-github-pages#1517]
I clicked accept ,but it says "This invitation is invalid. "
@githubteacher

**Comment by brianamarie** [comment]
@zapper123 - I'm so sorry this issue has been overlooked for so long. Your invitation should now be valid: https://github.com/githubschool/on-demand-github-pages/invitations

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
