### ISSUE TITLE
No option to "fetch origin"

### ISSUE THREAD

**Issue by JillCrungus** [githubschool/on-demand-github-pages#1529]
@githubteacher I have my master branch selected however I have no way to push my changes. Instead of a "fetch origin" button I have a "Publish repository" button. Trying to use it gives me the error:

"Repository creation failed. (name already exists on this account)"

There doesn't seem to be any way to get GH desktop to recognize that I already have a repository published.

I was previously using the Git GUI to commit and push changes however I've decided that I'd much rather use GitHub Desktop for the useful features it brings.

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.

**Comment by brianamarie** [comment]
@JillCrungus Have you been able to add the repository through the option to add an existing repository? Let me know if you need more help, sorry we didn't see this until now.
