### ISSUE TITLE
GitHub Desktop for Linux Mint?

### ISSUE THREAD

**Issue by alpereira7** [githubschool/on-demand-github-pages#1553]
Hi, @githubteacher I'm reading this page: https://services.github.com/on-demand/github-desktop/install-github-desktop

I would like to download GitHub Desktop at this page: https://desktop.github.com/
I can't find the version for my Linux Mint computer (only Windows and Mac).

Is there any other page I should go?

Regards.

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.

**Comment by alpereira7** [comment]
Well, I could merge my pull request by working on a Windows computer... I guess it's not possible to do it on Linux Mint. Thanks anyway...
