### ISSUE TITLE
I need help with connecting to our organisation github @githubteacher

### ISSUE THREAD

**Issue by lida-d** [githubschool/on-demand-github-pages#1570]
Hello,
I am following GitHub 102. I installed GitHub Desktop. I am connecting to our enterprise server.  
And it does not work.
I can access our enterprise github with web-browser. 
And I was able to sign in to my private free account on github.com
What is my issue with the enterprise server?
Thank you @githubteacher

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.

**Comment by brianamarie** [comment]
Hi @lida-d! Without looking at your computer, I think the best thing to do would be to 
- Re-install Desktop and try again
- Contact your GHE Admin

Let me know if I can help any more!
