### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by Johnos8** [githubschool/on-demand-github-pages#1572]
I'm puzzled and confused with all this local remote push pulletc.

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.

**Comment by brianamarie** [comment]
@Johnos8 I've closed this issue since it's been some time, but can I help with your question? Can you be a little more specific about where in the activities you have questions?

**Comment by Johnos8** [comment]
hello,
My apologies for not updating you. All Ok for  the moment. Thank  you for
your help.
jh
