### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by gilavraham** [githubschool/on-demand-github-pages#1584]
Using github desktop, after pull, how can I know if running bundle install and/or db migrate is required?

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.

**Comment by brianamarie** [comment]
> Using github desktop, after pull, how can I know if running bundle install and/or db migrate is required?

Hi @gilavraham! :wave: I think it depends on a project-by-project basis. I'm sorry that I can't be more help.
