### ISSUE TITLE
Request push access carouselling 2nd

### ISSUE THREAD

**Issue by carouselling** [githubschool/on-demand-github-pages#1594]
@githubteacher

**Comment by carouselling** [comment]
Hi @githubteacher , when I click "accept my invitation", it says that the invitation is invalid. Could you help me with this issue please? Thanks.

**Comment by brianamarie** [comment]
Hi @carouselling! I'm sorry about that - Try now, it should be working: https://github.com/githubschool/on-demand-github-pages/invitations

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
