### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by felipe-ba** [githubschool/on-demand-github-pages#1604]
pasa siempre esto...................
Alguna solución??????????
Commit failed - exit code 128 received, with output: '*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
