### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by haldekbartas** [githubschool/on-demand-github-pages#1611]
Please @githubteacher , could u help me ? I cant accept invitation "This invitation is invalid."

**Comment by brianamarie** [comment]
Hi @haldekbartas! Sorry about that - our bot has had a few glitches lately. If you try the link again, it should work now. 😄

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
