### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by BlackPhat** [githubschool/on-demand-github-pages#1612]
There is a disconnect when I try the following:

Open the file named README.md.
Remove the template text that was added to the README.md when you selected your theme.
In the README.md file include at least the following two lines: # Hello World! and My name is GITHUB_USERNAME. Bonus points for including more information.
When you are finished, save your changes and close the text editor.

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
