### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by coolc23** [githubschool/on-demand-github-pages#1624]
I chose the theme, but there was no filler that came up for me to commit the changes. What did I miss here?

**Comment by brianamarie** [comment]
Hi @coolc23! Good question. After you selected the theme, did it stick? Maybe we need to adjust our instructions to reflect that there's no "commit" message there?

cc/ @hectorsector

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
