### ISSUE TITLE
Every access to Git is denied when trying cloning repo through command line

### ISSUE THREAD

**Issue by NehaRuch** [githubschool/on-demand-github-pages#1705]
Every access I'm making for GIT like cloning, pushing, it displays result as "permission Denied"

**Comment by brianamarie** [comment]
Hi @NehaRuch! I'm sorry you're having that problem. There are a few things to check on - first, are you at work, at school, or at a computer that could be behind a firewall?

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
