### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by gonzamol** [githubschool/on-demand-github-pages#1713]
Hola, estoy intentando instalar Github Desktop pero me sale este error.
Lo tuve instalado hace tiempo pero lo desinstalé, al igual que Atom.
¿Alguien podría ayudarme?

Hi, Im trying to install Github Desktop but this error shows me.
A few time ago, it was installed in my PC but I removed it, same as Atom.
Can someone help me?

INFORMACIÓN DE VERSIÓN DE LA PLATAFORMA
Windows : 10.0.15063.0 (Win32NT)
Common Language Runtime : 4.0.30319.42000
System.Deployment.dll : 4.7.2046.0 built by: NET47REL1
clr.dll : 4.7.2115.0 built by: NET47REL1LAST
dfdll.dll : 4.7.2046.0 built by: NET47REL1
dfshim.dll : 10.0.15063.0 (WinBuild.160101.0800)

ORÍGENES
Dirección URL de la implementación	: file:///C:/Users/usuario-toshiba/Downloads/GitHub.application

IDENTIDADES
Identidad de la implementación	: GitHub.application, Version=3.3.4.0, Culture=neutral, PublicKeyToken=317444273a93ac29, processorArchitecture=x86

RESUMEN DE LA APLICACIÓN
* Aplicación instalable.
* Confianza del parámetro url establecida.
RESUMEN DEL ERROR
Abajo se muestra un resumen de los errores; los detalles de estos errores se incluyen en el registro.
* La activación de C:\Users\usuario-toshiba\Downloads\GitHub.application dio como resultado una excepción. Se detectaron los siguientes mensajes de error:
+ La implementación y la aplicación no tienen zonas de seguridad coincidentes.

RESUMEN DE ERRORES DE TRANSACCIÓN DEL ALMACÉN DE COMPONENTES
No se detectó ningún error de transacción.

ADVERTENCIAS
No se generó ninguna advertencia durante esta operación.

ESTADO DE PROGRESO DE LA OPERACIÓN
* [23/11/2017 11:11:23] : Se ha iniciado la activación de C:\Users\usuario-toshiba\Downloads\GitHub.application.
* [23/11/2017 11:11:32] : El procesamiento del manifiesto de la implementación finalizó correctamente.
* [23/11/2017 11:11:32] : Se ha iniciado la instalación de la aplicación.

DETALLES DEL ERROR
Se detectaron los siguientes errores durante esta operación.
* [23/11/2017 11:11:32] System.Deployment.Application.InvalidDeploymentException (Zone)
- La implementación y la aplicación no tienen zonas de seguridad coincidentes.
- Origen: System.Deployment
- Seguimiento de la pila:
en System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)
en System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
en System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
en System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
en System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
en System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
en System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

DETALLES DE TRANSACCIÓN DEL ALMACÉN DE COMPONENTES
No hay información disponible sobre la transacción.

**Comment by gonzamol** [comment]
@hectorsector please help!

**Comment by hectorsector** [comment]
👋 hola @gonzamol. Te sugiero que le preguntes a nuestro [departamento de ayuda](https://github.com/contact). También encontré esta [respuesta en StackOverflow](https://stackoverflow.com/a/33021657) que podría ser util.
