### ISSUE TITLE
req

### ISSUE THREAD

**Issue by carlasanches** [githubschool/on-demand-github-pages#1714]
request tutorial

**Comment by crichID** [comment]
@carlasanches it looks like you still need to accept the invitation we emailed you to become a collaborator on this repository! For a shortcut, you can also click [here](https://github.com/githubschool/on-demand-github-pages/invitations).

Once you have accepted the invitation, you will be ready for the next steps.

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
