### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by webizsoftware** [githubschool/on-demand-github-pages#1766]
when i click on branch to create new branch....it disable all option from branch menu in githu
![branch](https://user-images.githubusercontent.com/33750876/33549749-98a6ba28-d911-11e7-80a3-0753c3e940ac.png)
b desktop app

**Comment by crichID** [comment]
@webizsoftware Can you confirm the version of GitHub Desktop you are using and whether you are on a Windows or Mac?
