### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by Justme764** [githubschool/on-demand-github-pages#1821]
hello.  I can't seem to find the #4 of this lesson. click pull origin so I can push my page to gitHub. Thanks

**Comment by hectorsector** [comment]
@Justme764 I don't know I understand the question. Could you drop a link to the page that you're getting stuck in? I'll be glad to help.

**Comment by Justme764** [comment]
@githubteacher  here is the URL
https://services.github.com/on-demand/github-desktop/push-with-github-desktop
number 4 is where I'm having a issue.  Can't find pull origin button I would assume or I'm just reading it wrong.  Thanks for any help.

**Comment by hectorsector** [comment]
@Justme764 do you see "Fetch origin"?

**Comment by Justme764** [comment]
@hectorsector  Thank you very much for the help.  I will move on to the next lesson.
