### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by amankhanp** [githubschool/on-demand-github-pages#1860]
i need to upload my java code in github i'm new to this.

**Comment by crichID** [comment]
> i need to upload my java code in github i'm new to this.

@amankhanp are you using a development environment? Or the command line?

**Comment by amankhanp** [comment]
development environment

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
