### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by ktsak** [githubschool/on-demand-github-pages#1861]
I clone a repo from github with these instructions: https://services.github.com/on-demand/github-cli/create-branches-git and I would like to ask what should be showed after the "git status".I have this as a response" # On branch master nothing to commit (working directory clean)". Do I have to do something else to complete the clone procedure?

Thank you in advance!

**Comment by crichID** [comment]
> I clone a repo from github with these instructions: https://services.github.com/on-demand/github-cli/create-branches-git and I would like to ask what should be showed after the "git status".I have this as a response" # On branch master nothing to commit (working directory clean)". Do I have to do something else to complete the clone procedure?

@ktsak no, this is correct. After you  have cloned you will see this message that is saying you have not made any changes yet. Simply check out to your  branch with  `git checkout  branch-name` and begin making your changes.

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
