### ISSUE TITLE
help wanted please

### ISSUE THREAD

**Issue by Justme764** [githubschool/on-demand-github-pages#1866]
@githubteacher 

I have done the online class 101 102 103.  my issue is every time I try and view my page I get a 404 not found error.  if I replace the end IO with .com I get the below.  I get what it telling me but what I don't understand is "If you're the owner (which I am) of this site, please update your links to use Justme764.github.io" 

How do I update my links.  Very confused.  LOL  thanks for any help

404
There isn't a GitHub Pages site here.
Did you mean to visit Justme764.github.io? Please note that this site belongs to a GitHub user and is not an official GitHub site.
If you're the owner of this site, please update your links to use Justme764.github.io instead. Subdomains of github.com are deprecated for GitHub Pages. They will not redirect to github.io for new GitHub Pages sites.

**Comment by crichID** [comment]
@Justme764 did you enable GitHub pages on the repository? You will need to access the repository settings and use the drop  down under Pages to select Master.

**Comment by Justme764** [comment]
ahhh got it thanks.  was just using https://justme-GITHUB.IO/  instead of https://justme764.github.io/justme-GITHUB.IO/
