### ISSUE TITLE
ASAP!!!I need help!!!!!

### ISSUE THREAD

**Issue by Caseypongonis** [githubschool/on-demand-github-pages#1867]
I have my files and folders created in the GitHub Web browser- the remote server if you will. And I have that same repository opened up in Github Desktop. The history is all there and correct, but there is nothing in my changes section which I need there to be so I can "commit to master" and get my public URL.....Please Help Soon!

**Comment by crichID** [comment]
> I have my files and folders created in the GitHub Web browser- the remote server if you will. And I have that same repository opened up in Github Desktop. The history is all there and correct, but there is nothing in my changes section which I need there to be so I can "commit to master" and get my public URL.....Please Help Soon!

@Caseypongonis when you created the files, did you  save them in  your text editor? You will  need to save your changes before they will show up  in the changes  section   of desktop!

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
