### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by aliraj** [githubschool/on-demand-github-pages#1874]
![network](https://user-images.githubusercontent.com/17347382/34310387-9aabd94c-e781-11e7-8520-b8fb83dca8b7.gif)

Describe what you need help with here.

**Comment by aliraj** [comment]
![network](https://user-images.githubusercontent.com/17347382/34310436-bf59a6b6-e781-11e7-98ad-356af6885e16.gif)

**Comment by crichID** [comment]
@aliraj can  you please let me know how I  can help you?

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
