### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by ubet8932** [githubschool/on-demand-github-pages#1875]
How do I get the window pop-up of "enter the path for the new file" in Github desktop

**Comment by crichID** [comment]
> How do I get the window pop-up of "enter the path for the new file" in Github desktop

@ubet8932 are you referring to creating a new file?  You would create new files in your favorite text editor -- not  in GitHub desktop.

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
