### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by JuantaDev** [githubschool/on-demand-github-pages#1900]
Cuando abro github pages, se abre el readme del proyecto, y no mi proyecto ;(

**Comment by brianamarie** [comment]
Hi @hectorsector! If you have the bandwidth this week, do you mind taking a peek at this issue?

**Comment by JuantaDev** [comment]
hello, I solved the problem, I had configured another master branch to my project, and github pages has as reference the master branch that git has by default.

to fix it, I reconfigured the master branch that github has by default and I did a merge to the branch that previously had as "master" and after that github pages worked perfect.

thank you very much!
