### ISSUE TITLE
I need help syncing my github repository between 2 computers that I work on

### ISSUE THREAD

**Issue by alexisfischer** [githubschool/on-demand-github-pages#1901]
Hi! I am confused about how to sync a github repository between 2 computers - I tried reading the help boards, but got even more confused. Please advise! I originally set up the repository on one computer that I don't work on that much. I cloned this repository on a new computer and mostly work on this new computer. Problem is, is that all the changes that I make to the code on my new computer, do not sync with the master. Thank you :)

**Comment by brianamarie** [comment]
Hi @alexisfischer! 

So, this is a GREAT question. The best way to sync a repository between two computers is to use `git pull` and `git push` from both computers while you're working. 

When you type `git push`, anything that's been committed on a branch will then be pushed up to the remote repository. This only works for the branch that you're currently checked out to, so if you've been working on multiple branches, make sure you push all of them.

Then, when you get to your other computer, type `git pull`. Whatever branch you're on will update with the commits that you pushed up to the remote. 

Does this help at all?

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
