### ISSUE TITLE
Commit to (branch_name) blue button in GitHub desktop not active

### ISSUE THREAD

**Issue by Mostafa-Fayed** [githubschool/on-demand-github-pages#1906]
when I use GitHub desktop for committing, the blue button named (commit to branch_name) not active.
another thing how can I add a new file to my local repository using GitHub for desktop?

**Comment by brianamarie** [comment]
Hi! I'm sorry to hear that there's some trouble with GitHub Desktop. Unfortunately, this sounds like a possible bug with GitHub Desktop. I recommend searching the [issues for that repository](https://github.com/desktop/desktop/issues). 

To add a new file with GitHub Desktop, you'd create the file in the directory with whatever tool you're using to edit files. (In explorer, in finder, or in your text editor.) Then, you'd "add" the file just like you'd add any other changes. 😄 Let me know if there's any other questions we can help with!
