### ISSUE TITLE
I require assistance

### ISSUE THREAD

**Issue by DUFC-Liam** [githubschool/on-demand-github-pages#1938]
It shows this:
![image](https://user-images.githubusercontent.com/25304583/34567872-d836f6c8-f15b-11e7-88a4-5d72fc8c0c2b.png)
but the file is like this
![image](https://user-images.githubusercontent.com/25304583/34567889-e9f950e0-f15b-11e7-9ac8-00010618d90d.png)

**Comment by DUFC-Liam** [comment]
@githubteacher

**Comment by brianamarie** [comment]
Hi @DUFC-Liam! That is pretty bizzare. Thank you for posting the screen shots, that makes it much easier to understand the problem. 

Could you please try two things for me, and let me know what the results are? 
1. In the CLI, type `ls -al` and take a screenshot of the result.
  - Based on what is in the explorer, I'd expect there to be no files here. It looks like your last commit was deleting things. If we see things in this directory in the CLI but not in explorer, that would be surprising.
1. Make sure that the case doesn't matter by trying to CD into the directory as it appears in explorer. 
  - Type `cd ~` to get to your root directory
  - Type `cd Documents/DISCORD/Bots/RootBot` 
  - Type `ls -al` 
  - Take a screenshot. I'm looking for if that changes anything with the file structure. 

Good luck!

**Comment by DUFC-Liam** [comment]
![image](https://user-images.githubusercontent.com/25304583/34569773-b4afb75c-f161-11e7-9a74-4a8155b84666.png)
^^ FIRST ONE ^^
![image](https://user-images.githubusercontent.com/25304583/34569816-d41ec22c-f161-11e7-8b9e-06768238bd57.png)
^^ AFTER FIRST SCREENSHOT I ADDED THE PACKAGE.JSON TO TEST IF THAT WOULD HELP ^^

**Comment by brianamarie** [comment]
In the first one, it looks like you typed `ls -al` while you were in your root directory. In the second screenshot, it looks like you see exactly what you'd expect. 

So, you have deleted the files in that repository on master. When you type `git pull`, this doesn't go back in time to overwrite the commits that you've made since that point in time. 

Is that what you're trying to do?

**Comment by DUFC-Liam** [comment]
I am trying to pull the entire repository regardless of what is in my local file.

Eg. Override my folder with the github files

**Comment by brianamarie** [comment]
Ah, okay. So in that case, you will probably want to use `git reset`. This can be a potentially destructive command, but it sounds like that's what you want. 

The first step is to find the commit ID that you want your repository to replicate. So, find the commit ID of the most recent commit on master on the remote. 

Then, type `git reset --hard <commitID>`, like `git reset --hard 1a338c`. Then, the "head" pointer that represents your current working directory will move to that commit, and your local file structure will match what you see on the remote. 

This will essentially delete the commits you've made since you've pulled, that you haven't pushed up to the remote yet.

**Comment by DUFC-Liam** [comment]
So for https://github.com/RootBotTeam/RootBot/ I would do

`git reset`
`git reset --hard b6003a2`

**Comment by brianamarie** [comment]
Close, you wouldn't need the first line. All you would need is `git reset --hard b6003a2`. 👍

**Comment by DUFC-Liam** [comment]
@brianamarie 
![image](https://user-images.githubusercontent.com/25304583/34571461-88cde2a8-f166-11e7-96d3-4a3d35fda8e1.png)

**Comment by brianamarie** [comment]
Yep, that looks expected @DUFC-Liam. If you do `ls -al` or look in file explorer, are your files back?

**Comment by DUFC-Liam** [comment]
![image](https://user-images.githubusercontent.com/25304583/34571536-b21fc306-f166-11e7-8233-8f2eba0f1999.png)

**Comment by brianamarie** [comment]
Hm, that's not what I expected. If you type `git status`, is there anything there?

**Comment by DUFC-Liam** [comment]
![image](https://user-images.githubusercontent.com/25304583/34571655-fd4f40ea-f166-11e7-8bed-413603154c1a.png)

**Comment by brianamarie** [comment]
Ooohhhh. I think I see what the problem might be. This `RootBot` repository is inside of other directories, `Documents`, `DISCORD`, and `Bots`. Are any of those directories git repositories?

**Comment by DUFC-Liam** [comment]
Do you have team viewerr? ahah

**Comment by brianamarie** [comment]
Unfortunately I can't get on a call right now. 😞 

You can check if the other directories are git repositories by typing: 
- `cd ..`, which should put you inside of `/Bots`. You can check this by typing `pwd`. 
- `git status`. You _should_ see `fatal: Not a git repository (or any of the parent directories): .git`. 
  - If it _doesn't_ say that, then type `ls -al`. Look for a `.git` directory. If there is a `.git` directory, then it's a git repository. If you want it to be a git repository, then delete the `RootBot` directory and reclone into another directory that isn't a git repository. If you _don't_ want it to be a git repository, delete the `.git` directory. 
- Repeat this by typing `cd ..` again, then `pwd` to check that you're in the right directory.

Does that make sense?

**Comment by DUFC-Liam** [comment]
![image](https://user-images.githubusercontent.com/25304583/34572119-7170c272-f168-11e7-9961-c58cf57f4a62.png)
![image](https://user-images.githubusercontent.com/25304583/34572152-891f3214-f168-11e7-8ba4-62437563f9f3.png)
![image](https://user-images.githubusercontent.com/25304583/34572213-b8ed9b20-f168-11e7-8719-ea445731b3cf.png)

**Comment by brianamarie** [comment]
You're on the right track. Do the `cd ..` one more time, and `ls -al`. I have a hunch that you might have accidentally initialized a git repository on your root directory.

**Comment by DUFC-Liam** [comment]
![image](https://user-images.githubusercontent.com/25304583/34572482-647d401c-f169-11e7-84e7-779424228237.png)

**Comment by brianamarie** [comment]
Yep, there's the problem. Okay. I'm sorry that this might be a little bit tricky for you to clean up. There are a few layers here. 

Layer 1: Delete the .git file here
- Type `rm -rf .git`. This will delete the tracking happening that's affecting all of the child directories. 

Layer 2: Clean up the files in this directory that are not meant to be there 
- This one is up to you, but it looks to me like the files from RootBot have gotten copied into this root directory, when you probably want them only to be in the directory you have specifically for RootBot. 

Layer 3: Ensure the existing RootBot repository you have locally is actually set up with the correct remote. 
- CD into RootBot: `cd Documents/DISCORD/Bots/RootBot`
- Type `git status`. There's a chance that this isn't a repository at all. If that's the case, it's probably best to delete this directory and reclone. 
  - If that's the case then: 
  - type `CD ..` and confirm you're in Bots by typing `pwd` 
  - Remove the RootBot directory: `rm -rf RootBot/` 
  - Reclone the RootBot repository: `git clone https://github.com/RootBotTeam/RootBot/`
  - Whenever you work on RootBot, CD into the RootBot directory. From where you currently would be, this would require `cd RootBot`. 
- If you type `git status` and it _is_ a repository, type `git remote -v` to ensure the remote URL listed matches the remote https://github.com/RootBotTeam/RootBot/. If that's the case, type `git pull` and try `ls -al` again.

**Comment by DUFC-Liam** [comment]
![image](https://user-images.githubusercontent.com/25304583/34573326-c72c6916-f16b-11e7-9ee7-6953b1fcc1a0.png)

**Comment by brianamarie** [comment]
Perfect! This is actually great news. Now, we don't want the `Bots` directory to be a git repository. 

- CD into the RootBot repository: `cd RootBot` 
- See the files there: `ls -al` 
- See the commit history matching the recent commits on the remote: `git log --oneline -10`

**Comment by DUFC-Liam** [comment]
oh wait aaahhh, let me check

**Comment by DUFC-Liam** [comment]
![image](https://user-images.githubusercontent.com/25304583/34573471-2d140950-f16c-11e7-9d3c-e40e64eecd86.png)
ill try a test push right now 1s

**Comment by DUFC-Liam** [comment]
It works now :D Thanks @brianamarie

**Comment by brianamarie** [comment]
Yay! I'm so glad. Great work @DUFC-Liam!
