### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by shannonbux** [githubschool/on-demand-github-pages#1986]
@githubteacher I followed all the steps to push commits from Git desktop to Github online, and when I clicked "open a new pull request," I'm not seeing any of my commits...it shows some old ones, but not the most recent ones. 

I'm worried that I clicked the "sync" button too early or too late on Git desktop!

**Comment by hectorsector** [comment]
@shannonbux before you opened this issue you didn't have collaborator access. I wonder if that was the problem? If not, send me a couple of screenshots of what you're seeing and I'll be glad to help!
