### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by lberke** [githubschool/on-demand-github-pages#2090]
I have both an enterprise version and non linked to Github desktop.  When I attempt to follow these instructions, this box pops up.
![image](https://user-images.githubusercontent.com/30327018/35297102-9ec41d02-0043-11e8-87df-8bab02a3e321.png)
Nothing happens in desktop.  Do I need to log out of enterprise?

If I try to clone from desktop instead, I get this error:
![image](https://user-images.githubusercontent.com/30327018/35297236-0093df86-0044-11e8-9039-66d8c0253d54.png)

**Comment by GeoZac** [comment]
Make sure you have network access to github ,these kind of errors pop because of network restrictions

**Comment by lberke** [comment]
I do have network access to GitHub since I was trying to clone the repo
from there. I suspect a proxy issue but no idea how to fix it.

**Comment by GeoZac** [comment]
I too had the issue on my university,so had to make my repo portable.Lucky
for me the repo was small
