### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by Marijnone** [githubschool/on-demand-github-pages#2192]
when i want to git push -u origin marijnone i get the error: error: src refspec marijnone does not match any.
error: failed to push some refs to 'https://github.com/githubschool/on-demand-github-pages.git'

**Comment by arr99** [comment]
我不是晚了，我的电脑被他们控制，他们用卑鄙然后给我 的手段骗我，我每天都在杀毒一天操作系统好几次都删除不掉他们用的软件控制我电脑。今天他们用360  和QQ管家骗死我了、他们告诉我说、管家给我消息说病毒不可怕叫我升级管家我就升级了。升级以后真的可以了杀死两个木马。清理好多垃圾，，我想这一次应该电脑有教了。然后给我说叫我吧手机联电脑清理病毒回的刚买手机的系统。我连上了了。电脑从没有像今天这样过一点都不卡用着电脑像国家领导人用电脑一样轻松，他叫我登录QQ我登录好几次登录不了。手机更换密码也更换不了。我心里想好奇怪，我有点怀疑
，，我就下载金山毒霸可是没有浏览器
他们浏览器全部删除显示浏览器病毒我用管家下载说不支持下载金山毒霸，我更加怀疑是骗局我就赶快拔电脑和手机联的数据线。刚刚把掉，我去弄电脑电脑基本卡死机。我换那个电脑那电脑卡死机。事情就是这样。我现在死的想法都有。我天天白天晚上的在网络上一年半的时间，班都不上了、老婆还天天骂要离婚，我都不知道，这是为什么，我今天想了好多。这个99用户名，不是什么被盗了。就是官方的人给我弄走了的。还不是一个两个人干的这个事情。。因为我的电脑给微软说过多次。微软也帮忙，给我系统帮忙给我恶意软件杀毒软件，但是给我多次没用杀掉过一个木马。我自己那买微软的365系统到现在都没用给我安装，所以说这些领导真的是黑心了、他们联系外面黑客和火这样干，我是一个老百姓也不知道这些事情给谁说。我想管理这些网络部门的大领导，应该好好看看下面员工都在干些什么事情，知法犯法，这样下去你也是个领导吧，他们这样下去会越来队伍庞大吧国家都控制了、我现在知道网络有多么黑暗，不说了领导，我以后不上网就是了。我都快50岁的人了。以后不上网就可以了、谢谢领导你，  99啊辉
------------------ 原始邮件 ------------------，




------------------ 原始邮件 ------------------
发件人: "teacherbot[bot]";<notifications@github.com>;
发送时间: 2018年2月8日(星期四) 晚上8:34
收件人: "githubschool/on-demand-github-pages"<on-demand-github-pages@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [githubschool/on-demand-github-pages] I need help (#2192)




Hi! I'm the friendly   of this repo.
 
We're happy you're here . Everyone is welcome here, so I'm making you a collaborator. This will give you access to commit on this repo. Please accept my invitation before moving on.
