### ISSUE TITLE
I need help. I try to publish.

### ISSUE THREAD

**Issue by gm9089zo** [githubschool/on-demand-github-pages#2417]
Hello, I opened my first GitHub with GitHub Desktop for Windows 10. My repository is Edureka-Python-Certification. How do I...

1) Synch my repository on my desktop with a new file, or a new version of the same file...
2) Synch my repository online with GitHub.com

**Comment by EdwinAVA** [comment]
@gm9089zo  check the following link with a series of short tutorials for using the desktop application
https://services.github.com/on-demand/github-desktop/. I hope this will help you :smile:  !
