### ISSUE TITLE
Push Access Issue

### ISSUE THREAD

**Issue by nitincgit** [githubschool/on-demand-github-pages#272]
Push access isue

**Comment by githubteacher** [comment]
:tada: @nitincgit you are now a repository collaborator. :balloon:

**Comment by kervince** [comment]
Please let me collaborate on this topic.

**Comment by gypn** [comment]
:smile:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
