### ISSUE TITLE
Request for Collaborator Status to Commit GitHub Page to Showcase Repo

### ISSUE THREAD

**Issue by lonesome-data** [githubschool/on-demand-github-pages#3307]
@githubteacher it is a pleasure to again collaborate.

Friendly 🤖 of this repo, I respectfully request collaborator status to gain access to commit (my GitHub page) on this repo (showcase).  

I look forward to your invitation to move on.

**Comment by beebus** [comment]
@lonesome-data ,
Go ahead and Close the issue since it has been resolved.
