### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by jjingco** [githubschool/on-demand-github-pages#3773]
the site doesn't seem to be working on my end. I thought I had labeled it properly.  Please help @githubteacher

**Comment by beebus** [comment]
@jjingco,

Your repo, [https://github.com/jjingco/GITHUB.IO](https://github.com/jjingco/GITHUB.IO), needs to be renamed from "GITHUB.IO" to "JJINGCO.GITHUB.IO". On the repo page, click "Settings", change the repo name as described above, and click "Rename". 

Then refer to steps outlined on [https://pages.github.com/](https://pages.github.com/)
