### ISSUE TITLE
**Scroll and Webview** not working on IOS app.

### ISSUE THREAD

**Issue by sandysandy7** [githubschool/on-demand-github-pages#3813]
Hi everyone, 
While testing Real Device Unable to switch contex to  Webview and Scroll on IOS is not at all working
Using
Appium 1.9.1
Real device :iPhone X(version 11.4)
X-code(Version 9.4.1)
Automation tool: xFramium

Appium Debu capabilities:
{
  "deviceName": "iphone X",
  "udid": "******",
  "platformName": "IOS",
  "platformVersion": "11.4",
  "bundleId": "***************"
}
Device Registry 
<device active="true" name="iphone X" os="IOS" osVersion="11.4" model="iphone X" manufacturer="Apple" availableDevices="1" driverType="APPIUM" >
  	<capability name="deviceName" class="STRING">iphone X</capability>
    <capability name="udid" class="STRING">******</capability>
    <capability name="platform" class="STRING">IOS</capability>
    <capability name="noReset" class="BOOLEAN">false</capability>
    <capability name="simpleIsVisibleCheck" class="BOOLEAN">true</capability>
    <capability name="WKWebView" class="BOOLEAN">true</capability>
    <capability name="startIWDP" class="BOOLEAN">true</capability>
    <capability name="absoluteWebLocations" class="BOOLEAN">true</capability>
    <capability name="enablePerformanceLogging" class="BOOLEAN">false</capability>

    
   <capability name="iosInstall" class="STRING">//10.2.69.24//Users//devry123//desktop//DeVry.ipa</capability>
   <capability name="appPackage" class="STRING">com.devry.mobileapps.devry.debug</capability>
    <capability name="bundleId" class="STRING">*****</capability>
    <capability name="autoGrantPermissions" class="BOOLEAN">true</capability>
    <capability name="autoscroll" class="BOOLEAN">true</capability>

anyone could help on this one?

Thanks..

**Comment by sandysandy7** [comment]
Could anyone assigned for this issue yet?

**Comment by beebus** [comment]
This isn't the forum for such a question.
