### ISSUE TITLE
Automatic page generator

### ISSUE THREAD

**Issue by Dusterix** [githubschool/on-demand-github-pages#3825]
Hi

in my settings > GitHub Pages, I do not see the option of automatic page generator.

Please let me know if it has been deprecated or am I missing out on something?

Thank You!

**Comment by beebus** [comment]
> Hi
> 
> in my settings > GitHub Pages, I do not see the option of automatic page generator.
> 
> Please let me know if it has been deprecated or am I missing out on something?
> 
> Thank You!

@Dusterix,

It looks like the exact thing you speak of has been phased out:|

https://dannguyen.github.io/github-for-portfolios/lessons/premanufactured-github-pages/

https://help.github.com/en/enterprise/2.14/user/articles/creating-pages-with-the-automatic-generator
