### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by spittis** [githubschool/on-demand-github-pages#3835]
My email isn't configuring?

$ git config --global s_pittis@fanshaweonline.ca
error: invalid key: s_pittis@fanshaweonline.ca

**Comment by beebus** [comment]
> My email isn't configuring?
> 
> $ git config --global [s_pittis@fanshaweonline.ca](mailto:s_pittis@fanshaweonline.ca)
> error: invalid key: [s_pittis@fanshaweonline.ca](mailto:s_pittis@fanshaweonline.ca)

https://stackoverflow.com/questions/3580802/how-to-use-git-git-config-global

Don't forget the quotation marks.
git config --global user.name "Your Name"
git config --global user.email "name@domain.example"
