### ISSUE TITLE
@githubteacher need help!

### ISSUE THREAD

**Issue by smdotcom** [githubschool/on-demand-github-pages#3907]
I am stuck in step 2 adding pages 
Why my request fails?

**Comment by beebus** [comment]
On your commit page, https://github.com/smdotcom/smdotcom.github.io/commits/master, I'm only seeing pull requests to/from other branches of the same local repo.

Refer to the steps on https://pages.github.com.

You'll eventually need to submit a pull request onto https://github.com/githubschool/on-demand-github-pages/tree/master/_pages with <username>.yaml
