### ISSUE TITLE
Please add me as collaborator

### ISSUE THREAD

**Issue by Coder-Mustafa** [githubschool/on-demand-github-pages#402]
hello:wave! please add me as collaborator.

**Comment by githubteacher** [comment]
:tada: @Coder-Mustafa you are now a repository collaborator. :balloon:

**Comment by Coder-Mustafa** [comment]
Thank You

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
