### ISSUE TITLE
Please add me as collaborator

### ISSUE THREAD

**Issue by JulianGarzon509** [githubschool/on-demand-github-pages#508]
Hello 👋!!! Please add me as collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @JulianGarzon509 you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
