### ISSUE TITLE
Please add me as a collaborator on this issue

### ISSUE THREAD

**Issue by OldHWGuy** [githubschool/on-demand-github-pages#595]
Hi :wave:! Please add me as a collaborator.

**Comment by githubteacher** [comment]
:tada: @OldHWGuy you are now a repository collaborator. :balloon:

**Comment by brianamarie** [comment]
Hi! Let me know if you want any help. I'm just a `@brianamarie` away. 

![](https://media.giphy.com/media/IThjAlJnD9WNO/giphy.gif)
