### ISSUE TITLE
Please add me as a collaborator.

### ISSUE THREAD

**Issue by sushchikh** [githubschool/on-demand-github-pages#698]
Hello :wave: Please addm me as a collaborator to this repo.
Have a nice day!

**Comment by githubteacher** [comment]
:tada: @sushchikh you are now a repository collaborator. :balloon:

**Comment by sushchikh** [comment]
Wonderful! :ru:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
