### ISSUE TITLE
Hello, please add me as a collaborator! 

### ISSUE THREAD

**Issue by EllenaWarrantGroup** [githubschool/on-demand-github-pages#830]
Hi fellow Gits, please add me to this repository. :)

**Comment by githubteacher** [comment]
:tada: @EllenaWarrantGroup you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
