### ISSUE TITLE
Please Add Me As A Collaborator

### ISSUE THREAD

**Issue by paulnorthpole** [githubschool/on-demand-github-pages#868]
Hello 👍 ! Please add me as a collaborator to this repo.

**Comment by githubteacher** [comment]
:tada: @paulnorthpole you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
