### ISSUE TITLE
Would like to be added

### ISSUE THREAD

**Issue by jvjishnu** [githubschool/on-demand-github-pages#883]
Please add as collaborator :wave: 
@githubrobot @githubstudent @githubteacher

**Comment by githubteacher** [comment]
:tada: @jvjishnu you are now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
It looks like you have already merged your pull request or you stopped working on the activity. I'm going to go ahead and close this issue to keep the repository tidy.
